#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__ . '/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
$status = (require_once __DIR__ . '/bootstrap/app.php')
    ->handleCommand(new ArgvInput);

exit($status);

/*
php artisan serve
php artisan migrate:status
php artisan migrate
php artisan make:controller "EventController"
php artisan make:model "Event"
php artisan make:migration create_events_table
php artisan make:migration add_image_to_events_table
php artisan make:migration add_items_to_events_table
php artisan make:migration add_date_to_events_table
php artisan make:migration create_event_user_table
php artisan migrate:fresh

composer require laravel/jetstream
php artisan jetstream:install livewire
*/
