#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

// Register the Composer autoloader...
require __DIR__ . '/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
$status = (require_once __DIR__ . '/bootstrap/app.php')
    ->handleCommand(new ArgvInput);

exit($status);


/*
composer create-project laravel/laravel LivewirePro
php artisan make:livewire counter
create: app/Livewire/Counter.php
        resources/views/livewire/counter.blade.php

php artisan livewire:layout
create: resources/views/components/layouts/app.blade.php

php artisan serve
php artisan migrate:status
php artisan migrate:fresh
https://livewire.laravel.com/docs/quickstart
*/
